files: "^(src|tests)/"

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: local
    hooks:
      - name: mypy
        id: mypy
        entry: "./scripts/typecheck.sh"
        language: python
        types_or: [python, pyi]
        additional_dependencies: ["uv"]
