[build-system]
requires = ["uv_build>=0.9.17,<0.11.6"]
build-backend = "uv_build"

[project]
name = "confectioner"
version = "1.2.0"
authors = [
    {name = "Austin Warner", email = "austin.warner@8451.com"},
    {name = "Michael Stoepel", email = "michael.stoepel@8451.com"},
]
description = "A modular config framework for Python applications"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python",
]
dependencies = [
    "PyYAML>=5.0",
    "typing_extensions>=4.0; python_version<\"3.10\"",
]

[project.license]
file = "LICENSE"

[project.urls]
repository = "https://github.com/8451/confectioner"
documentation = "https://8451.github.io/confectioner"
bugs = "https://github.com/8451/confectioner/issues"

[dependency-groups]
docs = [
    "nbsphinx",
    "recommonmark",
    "sphinx",
    "sphinx_rtd_theme",
    "sphinxcontrib.napoleon",
    "myst-parser",
    "sphinxemoji",
]
lint = [
    "ruff"
]
test = [
    "coverage",
    "coverage-badge",
    "pytest",
    "pytest-cov",
]
typecheck = [
    "mypy",
    "types-pyyaml",
]
dev = [
    "bump2version",
    "pre-commit",
    {include-group = "docs"},
    {include-group = "lint"},
    {include-group = "test"},
    {include-group = "typecheck"},
]

[[tool.uv.index]]
url = "https://pypi.org/simple"
default = true

[tool.uv.sources]
confectioner = { workspace = true }
