# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on: [workflow_call, workflow_dispatch]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Lint with ruff
        if: ${{ matrix.python-version == '3.14' }}
        run: uv run --group lint ruff check src
      - name: Typecheck with mypy
        if: ${{ matrix.python-version == '3.14' }}
        run: uv run --group typecheck mypy src
      - name: Test with pytest
        run: |
          uv run --group test pytest --cov=confectioner --cov-report=xml
      - name: Update coverage badge
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.python-version == '3.14'}}
        run: |
          coverage-badge -o coverage.svg
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -f coverage.svg coverage.xml
          git commit -m $"Update coverage `date -u`"
          git fetch origin meta/coverage
          git checkout meta/coverage
          git pull
          git checkout main coverage.svg coverage.xml
          git commit -m $"Update coverage `date -u`"
          git push origin meta/coverage
